### PR TITLE
Remove pagination in 'Add repos' dialog

### LINKED ISSUE #383: [dashboard] alphabetically sort repositories and not paginate (0.5d)
Comments:

@magdalena_mir I believe so - I don't think we do any particular sorting, and things will go wrong if people have more than whatever the page size is of enabled repositories.  Not very urgent though.,@colinwatson4 is it still valid?,**Linked to** Dashboard: enabled repos view: https://projects.invisionapp.com/d/main#/console/10245106/218034262/preview

---
Creator: Robin Winslow
Assignees: Colin Watson
Copied from Trello card: https://trello.com/c/nXOUoeD6/114-dashboard-alphabetically-sort-repositories-and-not-paginate-0-5d
Labels: copy to github

### PR DESCRIPTION
**Pull request by bartaz**
## Done

Added loading all pages of repositories automatically and showing them all as one scrollable list in 'Add repos' dialog.

## QA

- Check out this feature branch
- Run the site using the command ```npm start -- --env=environments/dev.env```
- View the site locally in your web browser at: [http://0.0.0.0:8000/](http://0.0.0.0:8000/)
- Sign in and go to 'Add repos'
- All your repositories should be loaded into one long list without pagination

## Issue / Card

Fixes #383

### CODE REVIEW

File: src/common/components/select-repository-list/index.js [hunk 1]
```diff
@@ -117,32 +113,10 @@ export class SelectRepositoryListComponent extends Component {
...
-
-    return page;
-  }
-
   renderRepoList() {
-    const { ids, error, isFetching, isDelayed, pageLinks } = this.props.repositories;
+    const { ids, error, isFetching, isDelayed } = this.props.repositories;
 
-    if (isFetching) {
+    if (isFetching && ids.length === 0) {
```
Comment (bartaz) [inline src/common/components/select-repository-list/index.js]: Making sure we only show loading spinner when there are no repositories yet to avoid 'blinking' when subsequent pages are loaded in background.

**Comment by richmccartney** [comment]
👍 LGTM @bartaz
