### PR TITLE
Fixes alt text for images on the front page (fixing #874)

### LINKED ISSUE #874: Inappropriate jargon in alt text for hero image on front page
The alt text for the hero image on the front page is "Snapcraft hero image, push to GitHub, built automatically, release for your users."

"Hero image" is design jargon, and it does not belong in alt text whose primary audience should be users with accessibility needs.  The text of this attribute should be rephrased with consideration for those users.

### PR DESCRIPTION
**Pull request by matthewpaulthomas**
## Done

- Removes non-sequitur alt text for citation logos (adjacent text already names organizations)
- Removes alt text for hero image (redundant with text immediately below)
- Adds alt text for target OS logos
- Adds alt text for workflow diagram (since text is embedded in the image)
- Adds empty alt attribute for quality illustration (to avoid noise when reading)

## QA

- Read the front page using a text browser or screenreader.

## Issue / Card

Fixes #874.

### CODE REVIEW

File: src/common/components/testimonial/index.js [hunk 1]
```diff
@@ -9,7 +9,7 @@ export default function Testimonial(props) {
         <p>{ props.children }</p>
       </blockquote>
       <cite className={ style.pullQuoteCitation }>
-        <span className={ style.pullQuoteLogo }><img src={ props.logo } alt='logo'/></span> { props.citation }
+        <span className={ style.pullQuoteLogo }><img src={ props.logo } alt=''/></span> { props.citation }
```
Comment (richmccartney) [inline src/common/components/testimonial/index.js]: @matthewpaulthomas As much as the description has been removed, for a user whom is vision impaired this still doesn't explain to them what this logo is, who for, and why its here. Can we have a description please.

File: src/common/containers/landing.js [hunk 2]
```diff
@@ -27,7 +27,7 @@ class Landing extends Component {
 
               <ul className={ styles.banner }>
                 <li className={ styles.bannerImage }>
-                  <img src='https://assets.ubuntu.com/v1/ed6d1c5b-build.snapcraft.hero.svg' alt="Snapcraft hero image, push to GitHub, built automatically, release for your users."/>
+                  <img src='https://assets.ubuntu.com/v1/ed6d1c5b-build.snapcraft.hero.svg' alt=""/>
```
Comment (richmccartney) [inline src/common/containers/landing.js]: Again, alt text should be used for when the image can't be displayed or users that are using a screen reader and are vision impared. Removing the alt text is a detriment for this, instead of removing the alt can you look to improve it.

A good example post of how to write alt attribute content can be found here https://www.phase2technology.com/blog/no-more-excuses-definitive-guide-alt-text-field

File: src/common/containers/landing.js [hunk 3]
```diff
@@ -64,12 +64,12 @@ class Landing extends Component {
...
-              <img className={ styles.brandLogo } src={images.archlinux} />
-              <img className={ styles.brandLogo } src={images.gentoo} />
-              <img className={ styles.brandLogo } src={images.fedora} />
-              <img className={ styles.brandLogo } src={images.ubuntu} />
+              <img className={ styles.brandLogo } alt="Debian," src={images.debian} />
+              <img className={ styles.brandLogo } alt="openSUSE," src={images.opensuse} />
+              <img className={ styles.brandLogo } alt="Arch Linux," src={images.archlinux} />
+              <img className={ styles.brandLogo } alt="Gentoo," src={images.gentoo} />
+              <img className={ styles.brandLogo } alt="Fedora," src={images.fedora} />
+              <img className={ styles.brandLogo } alt="Ubuntu." src={images.ubuntu} />
```
Comment (richmccartney) [inline src/common/containers/landing.js]: Can we say more than just the logo company, we need to explain that his is the logo of that particular company.

File: src/common/containers/landing.js [hunk 4]
```diff
@@ -125,7 +125,7 @@ class Landing extends Component {
               </div>
             </div>
             <div className={styles.oneThird}>
-              <img src='https://assets.ubuntu.com/v1/2c5e93c5-fast-easy-safe-illustration.svg'/>
+              <img alt="" src='https://assets.ubuntu.com/v1/2c5e93c5-fast-easy-safe-illustration.svg'/>
```
Comment (richmccartney) [inline src/common/containers/landing.js]: Same comments as before.

File: src/common/containers/landing.js (hunk 2 above)
Comment (matthewpaulthomas) [inline src/common/containers/landing.js]: @richmccartney Unfortunately, that article is completely incorrect. It repeatedly refers to `alt` text as a “description” or “describing” an image, [directly contradicting the HTML specification](https://html.spec.whatwg.org/multipage/images.html#a-phrase-or-paragraph-with-an-alternative-graphical-representation:-charts,-diagrams,-graphs,-maps,-illustrations): “It is important to realize that the alternative text is a *replacement* for the image, not a description of the image”.

In this case, as I said in the PR, the `alt` text I removed was “redundant with text immediately below”. This is exactly [as recommended by the HTML spec](https://html.spec.whatwg.org/multipage/images.html#general-guidelines): “the `alt` attribute's value should not repeat information that is already provided in the prose next to the image.”

File: src/common/containers/landing.js (hunk 3 above)
Comment (matthewpaulthomas) [inline src/common/containers/landing.js]: @richmccartney Again, [the HTML spec addresses precisely this point](https://html.spec.whatwg.org/multipage/images.html#a-short-phrase-or-label-with-an-alternative-graphical-representation:-icons,-logos): “If the logo is being used to represent the entity, e.g. as a page heading, the `alt` attribute must contain the name of the entity being represented by the logo. The `alt` attribute must *not* contain text like the word ‘logo’, as it is not the fact that it is a logo that is being conveyed, it’s the entity itself.”

File: src/common/containers/landing.js (hunk 4 above)
Comment (matthewpaulthomas) [inline src/common/containers/landing.js]: @richmccartney This is a different kind of image from the previous ones. [To quote the HTML spec once more](https://html.spec.whatwg.org/multipage/images.html#a-purely-decorative-image-that-doesn%27t-add-any-information), it is “a decorative image that isn't discussed by the surrounding text but still has some relevance … In these cases, the `alt` attribute must be present but its value must be the empty string.”
